export const GET_PRODUCTS ="GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS ="GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE ="GET_PRODUCTS_FAILURE";

export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE="SEARCH_FAILURE";
export const SEARCH_TEXT="SEARCH_TEXT";

export const RELATED_PRODUCTS = "RELATED_PRODUCTS";
export const RELATED_PRODUCTS_SUCCESS = "RELATED_PRODUCTS_SUCCESS";
export const RELATED_PRODUCTS_FAILURE = "RELATED_PRODUCTS_FAILURE";
export const SEARCH_PROD = "SEARCH_PROD";